# Generated by Django 4.2.7 on 2024-01-13 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0089_log_entry_data_json_null_to_object'),
        ('donation', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DonationPageIndexPage',
            new_name='DonationIndexPage',
        ),
    ]
