# Generated by Django 4.2.7 on 2024-01-13 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0002_rename_donationpageindexpage_donationindexpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationindexpage',
            name='body',
            field=models.TextField(blank=True),
        ),
    ]
