# Generated by Django 4.2.7 on 2024-01-13 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0003_alter_donationindexpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationpage',
            name='body',
            field=models.TextField(blank=True),
        ),
    ]
