# Generated by Django 4.2.7 on 2023-11-22 19:47

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogpage_body_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='body_content',
            field=wagtail.fields.StreamField([('section', wagtail.blocks.StructBlock([('images', wagtail.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock(required=False)))]))], use_json_field=True),
        ),
    ]
