# Generated by Django 4.2.7 on 2023-11-23 16:22

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blogpage_body_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='body_content',
            field=wagtail.fields.StreamField([('section', wagtail.blocks.StructBlock([('images', wagtail.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock(required=False))), ('videos', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('video_url', wagtail.blocks.URLBlock(label='Video URL', required=False)), ('caption', wagtail.blocks.CharBlock(label='Caption', required=False))]), label='Videos', required=False))]))], blank=True, use_json_field=True),
        ),
    ]
