# Generated by Django 4.2.7 on 2024-01-18 14:20

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_blogpage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='body_content',
            field=wagtail.fields.StreamField([('section', wagtail.blocks.StructBlock([('images', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('title', wagtail.blocks.CharBlock(required=False)), ('caption', wagtail.blocks.CharBlock(label='Caption', required=False))]), label='Images', required=False)), ('videos', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=True)), ('video_url', wagtail.blocks.URLBlock(required=True))]), label='Videos', required=False))]))], blank=True, use_json_field=True),
        ),
    ]
