# Generated by Django 4.2.7 on 2024-01-18 14:28

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_blogpage_body_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='combined_content',
            field=wagtail.fields.StreamField([('combined_content', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=True)), ('video_url', wagtail.blocks.URLBlock(required=True)), ('rich_text_content', wagtail.blocks.RichTextBlock())]))], blank=True, use_json_field=True),
        ),
    ]
