# Generated by Django 4.2.7 on 2024-01-24 16:47

from django.db import migrations
import wagtail.blocks
import wagtail.embeds.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_blogpage_combined_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='body_video',
            field=wagtail.fields.StreamField([('video', wagtail.blocks.StructBlock([('video', wagtail.embeds.blocks.EmbedBlock(label='Video')), ('caption', wagtail.blocks.CharBlock(label='Caption', required=False)), ('float', wagtail.blocks.ChoiceBlock(choices=[('right', 'Right'), ('left', 'Left'), ('center', 'Center')], label='Float', required=False)), ('size', wagtail.blocks.ChoiceBlock(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], label='Size', required=False))]))], blank=True, use_json_field=True),
        ),
    ]
