# Generated by Django 4.2.7 on 2024-04-12 22:41

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.embeds.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
        ('home', '0004_homeindexpage_homepage_body_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeindexpage',
            name='body',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homeindexpage',
            name='body_content',
            field=wagtail.fields.StreamField([('section', wagtail.blocks.StructBlock([('images', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=False)), ('title', wagtail.blocks.CharBlock(required=False)), ('caption', wagtail.blocks.CharBlock(label='Caption', required=False))]), label='Images', required=False)), ('videos', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('video_url', wagtail.blocks.URLBlock(label='Video URL', required=False)), ('caption', wagtail.blocks.CharBlock(label='Caption', required=False))]), label='Videos', required=False))]))], blank=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='homeindexpage',
            name='body_video',
            field=wagtail.fields.StreamField([('video', wagtail.blocks.StructBlock([('video', wagtail.embeds.blocks.EmbedBlock(label='Video')), ('caption', wagtail.blocks.CharBlock(label='Caption', required=False)), ('float', wagtail.blocks.ChoiceBlock(choices=[('right', 'Right'), ('left', 'Left'), ('center', 'Center')], label='Float', required=False)), ('size', wagtail.blocks.ChoiceBlock(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], label='Size', required=False))]))], blank=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='homeindexpage',
            name='caption',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='homeindexpage',
            name='combined_content',
            field=wagtail.fields.StreamField([('combined_content', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(required=True)), ('video_url', wagtail.blocks.URLBlock(required=True)), ('rich_text_content', wagtail.blocks.RichTextBlock())]))], blank=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='homeindexpage',
            name='date',
            field=models.DateField(null=True, verbose_name='Post date'),
        ),
        migrations.AddField(
            model_name='homeindexpage',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homeindexpage',
            name='secondary_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.image'),
        ),
    ]
