# Generated by Django 4.2.7 on 2024-04-13 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_homeindexpage_body_homeindexpage_body_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeindexpage',
            name='body_content',
        ),
        migrations.RemoveField(
            model_name='homeindexpage',
            name='body_video',
        ),
        migrations.RemoveField(
            model_name='homeindexpage',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='homeindexpage',
            name='combined_content',
        ),
        migrations.RemoveField(
            model_name='homeindexpage',
            name='date',
        ),
        migrations.RemoveField(
            model_name='homeindexpage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='homeindexpage',
            name='secondary_image',
        ),
    ]
