# Generated by Django 4.2.7 on 2024-08-29 19:05

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('awards', '0004_alter_awardspage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awardspage',
            name='body',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
